---
language: java
jdk:
  - openjdk8
jobs:
  include:
    - stage: test
      script: "./build.sh"
    - stage: deploy
      script: "./deploy.sh"
env:
  - TROXY_DOCKER_IMAGE=docker.io/sparebank1/troxy
branches:
  only:
    - master
